### ISSUE TITLE
deglycosylated NPs?

### ISSUE THREAD

**Issue by fdamani** [apahl/rdkit_misc#1]
Hi Axel,

Thanks for some awesome python code to compute the NP-likeness scores following Ertl et. al 2008! Were you able to make any progress on deglycosylated the NPs? I didn't see a function for this in scaf_frag.py. Any recommendations on how to go about doing this? Thanks so much.

**Comment by apahl** [comment]
Hi Farhan,

we do indeed also still have the issue of deglycosylation. For a current project we are using the functionality included in KNIME. However, since the rest of the project pipeline is implemented in Python/RDKit, this is not a very good fit. We are seriously considering re-implementing this in Python/RDKit. If you would have examples of glycosylated NPs and their deglycosylated counterparts, it could help us in the development..

Kind regards,  
Axel

**Comment by fdamani** [comment]
Thanks for your message, Axel. Do you have a sense of what makes deglycosylation hard algorithmically? Shouldn't it be a simple substructure matching problem? e.g. take a list of sugar molecule SMILES strings and identify all substructures in NPs that match and then remove those strings.

**Comment by apahl** [comment]
Yes, in essence that's it, realized by a set of suitable SMARTS.  
But - not being a sugar expert - I expect that there are some weird corner cases for which it would be nice to have some examples.
